// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: elementproperties.proto

package com.tinkerpop.blueprints.impls.ramcloud;

public final class ElementPropertyProtos {
  private ElementPropertyProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface PropertyListOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // repeated .RamCloudGraph.Property property = 1;
    java.util.List<com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.Property> 
        getPropertyList();
    com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.Property getProperty(int index);
    int getPropertyCount();
    java.util.List<? extends com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.PropertyOrBuilder> 
        getPropertyOrBuilderList();
    com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.PropertyOrBuilder getPropertyOrBuilder(
        int index);
  }
  public static final class PropertyList extends
      com.google.protobuf.GeneratedMessage
      implements PropertyListOrBuilder {
    // Use PropertyList.newBuilder() to construct.
    private PropertyList(Builder builder) {
      super(builder);
    }
    private PropertyList(boolean noInit) {}
    
    private static final PropertyList defaultInstance;
    public static PropertyList getDefaultInstance() {
      return defaultInstance;
    }
    
    public PropertyList getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.internal_static_RamCloudGraph_PropertyList_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.internal_static_RamCloudGraph_PropertyList_fieldAccessorTable;
    }
    
    // repeated .RamCloudGraph.Property property = 1;
    public static final int PROPERTY_FIELD_NUMBER = 1;
    private java.util.List<com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.Property> property_;
    public java.util.List<com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.Property> getPropertyList() {
      return property_;
    }
    public java.util.List<? extends com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.PropertyOrBuilder> 
        getPropertyOrBuilderList() {
      return property_;
    }
    public int getPropertyCount() {
      return property_.size();
    }
    public com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.Property getProperty(int index) {
      return property_.get(index);
    }
    public com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.PropertyOrBuilder getPropertyOrBuilder(
        int index) {
      return property_.get(index);
    }
    
    private void initFields() {
      property_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      for (int i = 0; i < getPropertyCount(); i++) {
        if (!getProperty(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < property_.size(); i++) {
        output.writeMessage(1, property_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (int i = 0; i < property_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, property_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.PropertyList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.PropertyList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.PropertyList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.PropertyList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.PropertyList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.PropertyList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.PropertyList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.PropertyList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.PropertyList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.PropertyList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.PropertyList prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.PropertyListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.internal_static_RamCloudGraph_PropertyList_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.internal_static_RamCloudGraph_PropertyList_fieldAccessorTable;
      }
      
      // Construct using com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.PropertyList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getPropertyFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (propertyBuilder_ == null) {
          property_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          propertyBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.PropertyList.getDescriptor();
      }
      
      public com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.PropertyList getDefaultInstanceForType() {
        return com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.PropertyList.getDefaultInstance();
      }
      
      public com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.PropertyList build() {
        com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.PropertyList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.PropertyList buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.PropertyList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.PropertyList buildPartial() {
        com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.PropertyList result = new com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.PropertyList(this);
        int from_bitField0_ = bitField0_;
        if (propertyBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            property_ = java.util.Collections.unmodifiableList(property_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.property_ = property_;
        } else {
          result.property_ = propertyBuilder_.build();
        }
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.PropertyList) {
          return mergeFrom((com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.PropertyList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.PropertyList other) {
        if (other == com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.PropertyList.getDefaultInstance()) return this;
        if (propertyBuilder_ == null) {
          if (!other.property_.isEmpty()) {
            if (property_.isEmpty()) {
              property_ = other.property_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensurePropertyIsMutable();
              property_.addAll(other.property_);
            }
            onChanged();
          }
        } else {
          if (!other.property_.isEmpty()) {
            if (propertyBuilder_.isEmpty()) {
              propertyBuilder_.dispose();
              propertyBuilder_ = null;
              property_ = other.property_;
              bitField0_ = (bitField0_ & ~0x00000001);
              propertyBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getPropertyFieldBuilder() : null;
            } else {
              propertyBuilder_.addAllMessages(other.property_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        for (int i = 0; i < getPropertyCount(); i++) {
          if (!getProperty(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.Property.Builder subBuilder = com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.Property.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addProperty(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // repeated .RamCloudGraph.Property property = 1;
      private java.util.List<com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.Property> property_ =
        java.util.Collections.emptyList();
      private void ensurePropertyIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          property_ = new java.util.ArrayList<com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.Property>(property_);
          bitField0_ |= 0x00000001;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.Property, com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.Property.Builder, com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.PropertyOrBuilder> propertyBuilder_;
      
      public java.util.List<com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.Property> getPropertyList() {
        if (propertyBuilder_ == null) {
          return java.util.Collections.unmodifiableList(property_);
        } else {
          return propertyBuilder_.getMessageList();
        }
      }
      public int getPropertyCount() {
        if (propertyBuilder_ == null) {
          return property_.size();
        } else {
          return propertyBuilder_.getCount();
        }
      }
      public com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.Property getProperty(int index) {
        if (propertyBuilder_ == null) {
          return property_.get(index);
        } else {
          return propertyBuilder_.getMessage(index);
        }
      }
      public Builder setProperty(
          int index, com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.Property value) {
        if (propertyBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePropertyIsMutable();
          property_.set(index, value);
          onChanged();
        } else {
          propertyBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setProperty(
          int index, com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.Property.Builder builderForValue) {
        if (propertyBuilder_ == null) {
          ensurePropertyIsMutable();
          property_.set(index, builderForValue.build());
          onChanged();
        } else {
          propertyBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addProperty(com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.Property value) {
        if (propertyBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePropertyIsMutable();
          property_.add(value);
          onChanged();
        } else {
          propertyBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addProperty(
          int index, com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.Property value) {
        if (propertyBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePropertyIsMutable();
          property_.add(index, value);
          onChanged();
        } else {
          propertyBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addProperty(
          com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.Property.Builder builderForValue) {
        if (propertyBuilder_ == null) {
          ensurePropertyIsMutable();
          property_.add(builderForValue.build());
          onChanged();
        } else {
          propertyBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addProperty(
          int index, com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.Property.Builder builderForValue) {
        if (propertyBuilder_ == null) {
          ensurePropertyIsMutable();
          property_.add(index, builderForValue.build());
          onChanged();
        } else {
          propertyBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllProperty(
          java.lang.Iterable<? extends com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.Property> values) {
        if (propertyBuilder_ == null) {
          ensurePropertyIsMutable();
          super.addAll(values, property_);
          onChanged();
        } else {
          propertyBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearProperty() {
        if (propertyBuilder_ == null) {
          property_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          propertyBuilder_.clear();
        }
        return this;
      }
      public Builder removeProperty(int index) {
        if (propertyBuilder_ == null) {
          ensurePropertyIsMutable();
          property_.remove(index);
          onChanged();
        } else {
          propertyBuilder_.remove(index);
        }
        return this;
      }
      public com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.Property.Builder getPropertyBuilder(
          int index) {
        return getPropertyFieldBuilder().getBuilder(index);
      }
      public com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.PropertyOrBuilder getPropertyOrBuilder(
          int index) {
        if (propertyBuilder_ == null) {
          return property_.get(index);  } else {
          return propertyBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.PropertyOrBuilder> 
           getPropertyOrBuilderList() {
        if (propertyBuilder_ != null) {
          return propertyBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(property_);
        }
      }
      public com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.Property.Builder addPropertyBuilder() {
        return getPropertyFieldBuilder().addBuilder(
            com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.Property.getDefaultInstance());
      }
      public com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.Property.Builder addPropertyBuilder(
          int index) {
        return getPropertyFieldBuilder().addBuilder(
            index, com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.Property.getDefaultInstance());
      }
      public java.util.List<com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.Property.Builder> 
           getPropertyBuilderList() {
        return getPropertyFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.Property, com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.Property.Builder, com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.PropertyOrBuilder> 
          getPropertyFieldBuilder() {
        if (propertyBuilder_ == null) {
          propertyBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.Property, com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.Property.Builder, com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.PropertyOrBuilder>(
                  property_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          property_ = null;
        }
        return propertyBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:RamCloudGraph.PropertyList)
    }
    
    static {
      defaultInstance = new PropertyList(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:RamCloudGraph.PropertyList)
  }
  
  public interface PropertyOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string key = 1;
    boolean hasKey();
    String getKey();
    
    // required .RamCloudGraph.Property.Type value_type = 2;
    boolean hasValueType();
    com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.Property.Type getValueType();
    
    // optional string string_value = 3;
    boolean hasStringValue();
    String getStringValue();
    
    // optional int32 int32_value = 4;
    boolean hasInt32Value();
    int getInt32Value();
    
    // optional int64 int64_value = 5;
    boolean hasInt64Value();
    long getInt64Value();
    
    // optional double double_value = 6;
    boolean hasDoubleValue();
    double getDoubleValue();
    
    // optional float float_value = 7;
    boolean hasFloatValue();
    float getFloatValue();
    
    // optional bool bool_value = 8;
    boolean hasBoolValue();
    boolean getBoolValue();
  }
  public static final class Property extends
      com.google.protobuf.GeneratedMessage
      implements PropertyOrBuilder {
    // Use Property.newBuilder() to construct.
    private Property(Builder builder) {
      super(builder);
    }
    private Property(boolean noInit) {}
    
    private static final Property defaultInstance;
    public static Property getDefaultInstance() {
      return defaultInstance;
    }
    
    public Property getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.internal_static_RamCloudGraph_Property_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.internal_static_RamCloudGraph_Property_fieldAccessorTable;
    }
    
    public enum Type
        implements com.google.protobuf.ProtocolMessageEnum {
      STRING(0, 1),
      INT32(1, 2),
      INT64(2, 3),
      DOUBLE(3, 4),
      FLOAT(4, 5),
      BOOL(5, 6),
      ;
      
      public static final int STRING_VALUE = 1;
      public static final int INT32_VALUE = 2;
      public static final int INT64_VALUE = 3;
      public static final int DOUBLE_VALUE = 4;
      public static final int FLOAT_VALUE = 5;
      public static final int BOOL_VALUE = 6;
      
      
      public final int getNumber() { return value; }
      
      public static Type valueOf(int value) {
        switch (value) {
          case 1: return STRING;
          case 2: return INT32;
          case 3: return INT64;
          case 4: return DOUBLE;
          case 5: return FLOAT;
          case 6: return BOOL;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Type>() {
              public Type findValueByNumber(int number) {
                return Type.valueOf(number);
              }
            };
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.Property.getDescriptor().getEnumTypes().get(0);
      }
      
      private static final Type[] VALUES = {
        STRING, INT32, INT64, DOUBLE, FLOAT, BOOL, 
      };
      
      public static Type valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      
      private final int index;
      private final int value;
      
      private Type(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      // @@protoc_insertion_point(enum_scope:RamCloudGraph.Property.Type)
    }
    
    private int bitField0_;
    // required string key = 1;
    public static final int KEY_FIELD_NUMBER = 1;
    private java.lang.Object key_;
    public boolean hasKey() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getKey() {
      java.lang.Object ref = key_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          key_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getKeyBytes() {
      java.lang.Object ref = key_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        key_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required .RamCloudGraph.Property.Type value_type = 2;
    public static final int VALUE_TYPE_FIELD_NUMBER = 2;
    private com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.Property.Type valueType_;
    public boolean hasValueType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.Property.Type getValueType() {
      return valueType_;
    }
    
    // optional string string_value = 3;
    public static final int STRING_VALUE_FIELD_NUMBER = 3;
    private java.lang.Object stringValue_;
    public boolean hasStringValue() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getStringValue() {
      java.lang.Object ref = stringValue_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          stringValue_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getStringValueBytes() {
      java.lang.Object ref = stringValue_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        stringValue_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional int32 int32_value = 4;
    public static final int INT32_VALUE_FIELD_NUMBER = 4;
    private int int32Value_;
    public boolean hasInt32Value() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public int getInt32Value() {
      return int32Value_;
    }
    
    // optional int64 int64_value = 5;
    public static final int INT64_VALUE_FIELD_NUMBER = 5;
    private long int64Value_;
    public boolean hasInt64Value() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public long getInt64Value() {
      return int64Value_;
    }
    
    // optional double double_value = 6;
    public static final int DOUBLE_VALUE_FIELD_NUMBER = 6;
    private double doubleValue_;
    public boolean hasDoubleValue() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public double getDoubleValue() {
      return doubleValue_;
    }
    
    // optional float float_value = 7;
    public static final int FLOAT_VALUE_FIELD_NUMBER = 7;
    private float floatValue_;
    public boolean hasFloatValue() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    public float getFloatValue() {
      return floatValue_;
    }
    
    // optional bool bool_value = 8;
    public static final int BOOL_VALUE_FIELD_NUMBER = 8;
    private boolean boolValue_;
    public boolean hasBoolValue() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    public boolean getBoolValue() {
      return boolValue_;
    }
    
    private void initFields() {
      key_ = "";
      valueType_ = com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.Property.Type.STRING;
      stringValue_ = "";
      int32Value_ = 0;
      int64Value_ = 0L;
      doubleValue_ = 0D;
      floatValue_ = 0F;
      boolValue_ = false;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasKey()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasValueType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getKeyBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, valueType_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getStringValueBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, int32Value_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt64(5, int64Value_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeDouble(6, doubleValue_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeFloat(7, floatValue_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeBool(8, boolValue_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getKeyBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, valueType_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getStringValueBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, int32Value_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, int64Value_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(6, doubleValue_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(7, floatValue_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(8, boolValue_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.Property parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.Property parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.Property parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.Property parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.Property parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.Property parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.Property parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.Property parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.Property parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.Property parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.Property prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.PropertyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.internal_static_RamCloudGraph_Property_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.internal_static_RamCloudGraph_Property_fieldAccessorTable;
      }
      
      // Construct using com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.Property.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        key_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        valueType_ = com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.Property.Type.STRING;
        bitField0_ = (bitField0_ & ~0x00000002);
        stringValue_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        int32Value_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        int64Value_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000010);
        doubleValue_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000020);
        floatValue_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000040);
        boolValue_ = false;
        bitField0_ = (bitField0_ & ~0x00000080);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.Property.getDescriptor();
      }
      
      public com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.Property getDefaultInstanceForType() {
        return com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.Property.getDefaultInstance();
      }
      
      public com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.Property build() {
        com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.Property result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.Property buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.Property result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.Property buildPartial() {
        com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.Property result = new com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.Property(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.key_ = key_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.valueType_ = valueType_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.stringValue_ = stringValue_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.int32Value_ = int32Value_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.int64Value_ = int64Value_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.doubleValue_ = doubleValue_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.floatValue_ = floatValue_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.boolValue_ = boolValue_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.Property) {
          return mergeFrom((com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.Property)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.Property other) {
        if (other == com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.Property.getDefaultInstance()) return this;
        if (other.hasKey()) {
          setKey(other.getKey());
        }
        if (other.hasValueType()) {
          setValueType(other.getValueType());
        }
        if (other.hasStringValue()) {
          setStringValue(other.getStringValue());
        }
        if (other.hasInt32Value()) {
          setInt32Value(other.getInt32Value());
        }
        if (other.hasInt64Value()) {
          setInt64Value(other.getInt64Value());
        }
        if (other.hasDoubleValue()) {
          setDoubleValue(other.getDoubleValue());
        }
        if (other.hasFloatValue()) {
          setFloatValue(other.getFloatValue());
        }
        if (other.hasBoolValue()) {
          setBoolValue(other.getBoolValue());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasKey()) {
          
          return false;
        }
        if (!hasValueType()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              key_ = input.readBytes();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.Property.Type value = com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.Property.Type.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                valueType_ = value;
              }
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              stringValue_ = input.readBytes();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              int32Value_ = input.readInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              int64Value_ = input.readInt64();
              break;
            }
            case 49: {
              bitField0_ |= 0x00000020;
              doubleValue_ = input.readDouble();
              break;
            }
            case 61: {
              bitField0_ |= 0x00000040;
              floatValue_ = input.readFloat();
              break;
            }
            case 64: {
              bitField0_ |= 0x00000080;
              boolValue_ = input.readBool();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string key = 1;
      private java.lang.Object key_ = "";
      public boolean hasKey() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getKey() {
        java.lang.Object ref = key_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          key_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setKey(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        key_ = value;
        onChanged();
        return this;
      }
      public Builder clearKey() {
        bitField0_ = (bitField0_ & ~0x00000001);
        key_ = getDefaultInstance().getKey();
        onChanged();
        return this;
      }
      void setKey(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        key_ = value;
        onChanged();
      }
      
      // required .RamCloudGraph.Property.Type value_type = 2;
      private com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.Property.Type valueType_ = com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.Property.Type.STRING;
      public boolean hasValueType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.Property.Type getValueType() {
        return valueType_;
      }
      public Builder setValueType(com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.Property.Type value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        valueType_ = value;
        onChanged();
        return this;
      }
      public Builder clearValueType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        valueType_ = com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.Property.Type.STRING;
        onChanged();
        return this;
      }
      
      // optional string string_value = 3;
      private java.lang.Object stringValue_ = "";
      public boolean hasStringValue() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getStringValue() {
        java.lang.Object ref = stringValue_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          stringValue_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setStringValue(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        stringValue_ = value;
        onChanged();
        return this;
      }
      public Builder clearStringValue() {
        bitField0_ = (bitField0_ & ~0x00000004);
        stringValue_ = getDefaultInstance().getStringValue();
        onChanged();
        return this;
      }
      void setStringValue(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        stringValue_ = value;
        onChanged();
      }
      
      // optional int32 int32_value = 4;
      private int int32Value_ ;
      public boolean hasInt32Value() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public int getInt32Value() {
        return int32Value_;
      }
      public Builder setInt32Value(int value) {
        bitField0_ |= 0x00000008;
        int32Value_ = value;
        onChanged();
        return this;
      }
      public Builder clearInt32Value() {
        bitField0_ = (bitField0_ & ~0x00000008);
        int32Value_ = 0;
        onChanged();
        return this;
      }
      
      // optional int64 int64_value = 5;
      private long int64Value_ ;
      public boolean hasInt64Value() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public long getInt64Value() {
        return int64Value_;
      }
      public Builder setInt64Value(long value) {
        bitField0_ |= 0x00000010;
        int64Value_ = value;
        onChanged();
        return this;
      }
      public Builder clearInt64Value() {
        bitField0_ = (bitField0_ & ~0x00000010);
        int64Value_ = 0L;
        onChanged();
        return this;
      }
      
      // optional double double_value = 6;
      private double doubleValue_ ;
      public boolean hasDoubleValue() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public double getDoubleValue() {
        return doubleValue_;
      }
      public Builder setDoubleValue(double value) {
        bitField0_ |= 0x00000020;
        doubleValue_ = value;
        onChanged();
        return this;
      }
      public Builder clearDoubleValue() {
        bitField0_ = (bitField0_ & ~0x00000020);
        doubleValue_ = 0D;
        onChanged();
        return this;
      }
      
      // optional float float_value = 7;
      private float floatValue_ ;
      public boolean hasFloatValue() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      public float getFloatValue() {
        return floatValue_;
      }
      public Builder setFloatValue(float value) {
        bitField0_ |= 0x00000040;
        floatValue_ = value;
        onChanged();
        return this;
      }
      public Builder clearFloatValue() {
        bitField0_ = (bitField0_ & ~0x00000040);
        floatValue_ = 0F;
        onChanged();
        return this;
      }
      
      // optional bool bool_value = 8;
      private boolean boolValue_ ;
      public boolean hasBoolValue() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      public boolean getBoolValue() {
        return boolValue_;
      }
      public Builder setBoolValue(boolean value) {
        bitField0_ |= 0x00000080;
        boolValue_ = value;
        onChanged();
        return this;
      }
      public Builder clearBoolValue() {
        bitField0_ = (bitField0_ & ~0x00000080);
        boolValue_ = false;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:RamCloudGraph.Property)
    }
    
    static {
      defaultInstance = new Property(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:RamCloudGraph.Property)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_RamCloudGraph_PropertyList_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_RamCloudGraph_PropertyList_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_RamCloudGraph_Property_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_RamCloudGraph_Property_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027elementproperties.proto\022\rRamCloudGraph" +
      "\"9\n\014PropertyList\022)\n\010property\030\001 \003(\0132\027.Ram" +
      "CloudGraph.Property\"\223\002\n\010Property\022\013\n\003key\030" +
      "\001 \002(\t\0220\n\nvalue_type\030\002 \002(\0162\034.RamCloudGrap" +
      "h.Property.Type\022\024\n\014string_value\030\003 \001(\t\022\023\n" +
      "\013int32_value\030\004 \001(\005\022\023\n\013int64_value\030\005 \001(\003\022" +
      "\024\n\014double_value\030\006 \001(\001\022\023\n\013float_value\030\007 \001" +
      "(\002\022\022\n\nbool_value\030\010 \001(\010\"I\n\004Type\022\n\n\006STRING" +
      "\020\001\022\t\n\005INT32\020\002\022\t\n\005INT64\020\003\022\n\n\006DOUBLE\020\004\022\t\n\005" +
      "FLOAT\020\005\022\010\n\004BOOL\020\006B@\n\'com.tinkerpop.bluep",
      "rints.impls.ramcloudB\025ElementPropertyPro" +
      "tos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_RamCloudGraph_PropertyList_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_RamCloudGraph_PropertyList_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_RamCloudGraph_PropertyList_descriptor,
              new java.lang.String[] { "Property", },
              com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.PropertyList.class,
              com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.PropertyList.Builder.class);
          internal_static_RamCloudGraph_Property_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_RamCloudGraph_Property_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_RamCloudGraph_Property_descriptor,
              new java.lang.String[] { "Key", "ValueType", "StringValue", "Int32Value", "Int64Value", "DoubleValue", "FloatValue", "BoolValue", },
              com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.Property.class,
              com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.Property.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
