// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: elementproperties.proto

package com.tinkerpop.blueprints.impls.ramcloud;

public final class ElementPropertyProtos {
  private ElementPropertyProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface PropertyListOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // repeated .RamCloudGraph.Property property = 1;
    java.util.List<com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.Property> 
        getPropertyList();
    com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.Property getProperty(int index);
    int getPropertyCount();
    java.util.List<? extends com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.PropertyOrBuilder> 
        getPropertyOrBuilderList();
    com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.PropertyOrBuilder getPropertyOrBuilder(
        int index);
  }
  public static final class PropertyList extends
      com.google.protobuf.GeneratedMessage
      implements PropertyListOrBuilder {
    // Use PropertyList.newBuilder() to construct.
    private PropertyList(Builder builder) {
      super(builder);
    }
    private PropertyList(boolean noInit) {}
    
    private static final PropertyList defaultInstance;
    public static PropertyList getDefaultInstance() {
      return defaultInstance;
    }
    
    public PropertyList getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.internal_static_RamCloudGraph_PropertyList_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.internal_static_RamCloudGraph_PropertyList_fieldAccessorTable;
    }
    
    // repeated .RamCloudGraph.Property property = 1;
    public static final int PROPERTY_FIELD_NUMBER = 1;
    private java.util.List<com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.Property> property_;
    public java.util.List<com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.Property> getPropertyList() {
      return property_;
    }
    public java.util.List<? extends com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.PropertyOrBuilder> 
        getPropertyOrBuilderList() {
      return property_;
    }
    public int getPropertyCount() {
      return property_.size();
    }
    public com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.Property getProperty(int index) {
      return property_.get(index);
    }
    public com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.PropertyOrBuilder getPropertyOrBuilder(
        int index) {
      return property_.get(index);
    }
    
    private void initFields() {
      property_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      for (int i = 0; i < getPropertyCount(); i++) {
        if (!getProperty(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < property_.size(); i++) {
        output.writeMessage(1, property_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (int i = 0; i < property_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, property_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.PropertyList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.PropertyList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.PropertyList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.PropertyList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.PropertyList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.PropertyList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.PropertyList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.PropertyList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.PropertyList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.PropertyList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.PropertyList prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.PropertyListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.internal_static_RamCloudGraph_PropertyList_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.internal_static_RamCloudGraph_PropertyList_fieldAccessorTable;
      }
      
      // Construct using com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.PropertyList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getPropertyFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (propertyBuilder_ == null) {
          property_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          propertyBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.PropertyList.getDescriptor();
      }
      
      public com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.PropertyList getDefaultInstanceForType() {
        return com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.PropertyList.getDefaultInstance();
      }
      
      public com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.PropertyList build() {
        com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.PropertyList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.PropertyList buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.PropertyList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.PropertyList buildPartial() {
        com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.PropertyList result = new com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.PropertyList(this);
        int from_bitField0_ = bitField0_;
        if (propertyBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            property_ = java.util.Collections.unmodifiableList(property_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.property_ = property_;
        } else {
          result.property_ = propertyBuilder_.build();
        }
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.PropertyList) {
          return mergeFrom((com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.PropertyList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.PropertyList other) {
        if (other == com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.PropertyList.getDefaultInstance()) return this;
        if (propertyBuilder_ == null) {
          if (!other.property_.isEmpty()) {
            if (property_.isEmpty()) {
              property_ = other.property_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensurePropertyIsMutable();
              property_.addAll(other.property_);
            }
            onChanged();
          }
        } else {
          if (!other.property_.isEmpty()) {
            if (propertyBuilder_.isEmpty()) {
              propertyBuilder_.dispose();
              propertyBuilder_ = null;
              property_ = other.property_;
              bitField0_ = (bitField0_ & ~0x00000001);
              propertyBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getPropertyFieldBuilder() : null;
            } else {
              propertyBuilder_.addAllMessages(other.property_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        for (int i = 0; i < getPropertyCount(); i++) {
          if (!getProperty(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.Property.Builder subBuilder = com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.Property.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addProperty(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // repeated .RamCloudGraph.Property property = 1;
      private java.util.List<com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.Property> property_ =
        java.util.Collections.emptyList();
      private void ensurePropertyIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          property_ = new java.util.ArrayList<com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.Property>(property_);
          bitField0_ |= 0x00000001;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.Property, com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.Property.Builder, com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.PropertyOrBuilder> propertyBuilder_;
      
      public java.util.List<com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.Property> getPropertyList() {
        if (propertyBuilder_ == null) {
          return java.util.Collections.unmodifiableList(property_);
        } else {
          return propertyBuilder_.getMessageList();
        }
      }
      public int getPropertyCount() {
        if (propertyBuilder_ == null) {
          return property_.size();
        } else {
          return propertyBuilder_.getCount();
        }
      }
      public com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.Property getProperty(int index) {
        if (propertyBuilder_ == null) {
          return property_.get(index);
        } else {
          return propertyBuilder_.getMessage(index);
        }
      }
      public Builder setProperty(
          int index, com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.Property value) {
        if (propertyBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePropertyIsMutable();
          property_.set(index, value);
          onChanged();
        } else {
          propertyBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setProperty(
          int index, com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.Property.Builder builderForValue) {
        if (propertyBuilder_ == null) {
          ensurePropertyIsMutable();
          property_.set(index, builderForValue.build());
          onChanged();
        } else {
          propertyBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addProperty(com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.Property value) {
        if (propertyBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePropertyIsMutable();
          property_.add(value);
          onChanged();
        } else {
          propertyBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addProperty(
          int index, com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.Property value) {
        if (propertyBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePropertyIsMutable();
          property_.add(index, value);
          onChanged();
        } else {
          propertyBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addProperty(
          com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.Property.Builder builderForValue) {
        if (propertyBuilder_ == null) {
          ensurePropertyIsMutable();
          property_.add(builderForValue.build());
          onChanged();
        } else {
          propertyBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addProperty(
          int index, com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.Property.Builder builderForValue) {
        if (propertyBuilder_ == null) {
          ensurePropertyIsMutable();
          property_.add(index, builderForValue.build());
          onChanged();
        } else {
          propertyBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllProperty(
          java.lang.Iterable<? extends com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.Property> values) {
        if (propertyBuilder_ == null) {
          ensurePropertyIsMutable();
          super.addAll(values, property_);
          onChanged();
        } else {
          propertyBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearProperty() {
        if (propertyBuilder_ == null) {
          property_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          propertyBuilder_.clear();
        }
        return this;
      }
      public Builder removeProperty(int index) {
        if (propertyBuilder_ == null) {
          ensurePropertyIsMutable();
          property_.remove(index);
          onChanged();
        } else {
          propertyBuilder_.remove(index);
        }
        return this;
      }
      public com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.Property.Builder getPropertyBuilder(
          int index) {
        return getPropertyFieldBuilder().getBuilder(index);
      }
      public com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.PropertyOrBuilder getPropertyOrBuilder(
          int index) {
        if (propertyBuilder_ == null) {
          return property_.get(index);  } else {
          return propertyBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.PropertyOrBuilder> 
           getPropertyOrBuilderList() {
        if (propertyBuilder_ != null) {
          return propertyBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(property_);
        }
      }
      public com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.Property.Builder addPropertyBuilder() {
        return getPropertyFieldBuilder().addBuilder(
            com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.Property.getDefaultInstance());
      }
      public com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.Property.Builder addPropertyBuilder(
          int index) {
        return getPropertyFieldBuilder().addBuilder(
            index, com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.Property.getDefaultInstance());
      }
      public java.util.List<com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.Property.Builder> 
           getPropertyBuilderList() {
        return getPropertyFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.Property, com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.Property.Builder, com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.PropertyOrBuilder> 
          getPropertyFieldBuilder() {
        if (propertyBuilder_ == null) {
          propertyBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.Property, com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.Property.Builder, com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.PropertyOrBuilder>(
                  property_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          property_ = null;
        }
        return propertyBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:RamCloudGraph.PropertyList)
    }
    
    static {
      defaultInstance = new PropertyList(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:RamCloudGraph.PropertyList)
  }
  
  public interface PropertyOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required .RamCloudGraph.Property.Type type = 1;
    boolean hasType();
    com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.Property.Type getType();
    
    // optional string string = 2;
    boolean hasString();
    String getString();
    
    // optional int64 int64 = 3;
    boolean hasInt64();
    long getInt64();
    
    // optional double double = 4;
    boolean hasDouble();
    double getDouble();
    
    // optional float float = 5;
    boolean hasFloat();
    float getFloat();
    
    // optional bool bool = 6;
    boolean hasBool();
    boolean getBool();
  }
  public static final class Property extends
      com.google.protobuf.GeneratedMessage
      implements PropertyOrBuilder {
    // Use Property.newBuilder() to construct.
    private Property(Builder builder) {
      super(builder);
    }
    private Property(boolean noInit) {}
    
    private static final Property defaultInstance;
    public static Property getDefaultInstance() {
      return defaultInstance;
    }
    
    public Property getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.internal_static_RamCloudGraph_Property_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.internal_static_RamCloudGraph_Property_fieldAccessorTable;
    }
    
    public enum Type
        implements com.google.protobuf.ProtocolMessageEnum {
      STRING(0, 1),
      INT64(1, 2),
      DOUBLE(2, 3),
      FLOAT(3, 4),
      BOOL(4, 5),
      ;
      
      public static final int STRING_VALUE = 1;
      public static final int INT64_VALUE = 2;
      public static final int DOUBLE_VALUE = 3;
      public static final int FLOAT_VALUE = 4;
      public static final int BOOL_VALUE = 5;
      
      
      public final int getNumber() { return value; }
      
      public static Type valueOf(int value) {
        switch (value) {
          case 1: return STRING;
          case 2: return INT64;
          case 3: return DOUBLE;
          case 4: return FLOAT;
          case 5: return BOOL;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Type>() {
              public Type findValueByNumber(int number) {
                return Type.valueOf(number);
              }
            };
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.Property.getDescriptor().getEnumTypes().get(0);
      }
      
      private static final Type[] VALUES = {
        STRING, INT64, DOUBLE, FLOAT, BOOL, 
      };
      
      public static Type valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      
      private final int index;
      private final int value;
      
      private Type(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      // @@protoc_insertion_point(enum_scope:RamCloudGraph.Property.Type)
    }
    
    private int bitField0_;
    // required .RamCloudGraph.Property.Type type = 1;
    public static final int TYPE_FIELD_NUMBER = 1;
    private com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.Property.Type type_;
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.Property.Type getType() {
      return type_;
    }
    
    // optional string string = 2;
    public static final int STRING_FIELD_NUMBER = 2;
    private java.lang.Object string_;
    public boolean hasString() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getString() {
      java.lang.Object ref = string_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          string_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getStringBytes() {
      java.lang.Object ref = string_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        string_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional int64 int64 = 3;
    public static final int INT64_FIELD_NUMBER = 3;
    private long int64_;
    public boolean hasInt64() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public long getInt64() {
      return int64_;
    }
    
    // optional double double = 4;
    public static final int DOUBLE_FIELD_NUMBER = 4;
    private double double_;
    public boolean hasDouble() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public double getDouble() {
      return double_;
    }
    
    // optional float float = 5;
    public static final int FLOAT_FIELD_NUMBER = 5;
    private float float_;
    public boolean hasFloat() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public float getFloat() {
      return float_;
    }
    
    // optional bool bool = 6;
    public static final int BOOL_FIELD_NUMBER = 6;
    private boolean bool_;
    public boolean hasBool() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public boolean getBool() {
      return bool_;
    }
    
    private void initFields() {
      type_ = com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.Property.Type.STRING;
      string_ = "";
      int64_ = 0L;
      double_ = 0D;
      float_ = 0F;
      bool_ = false;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getStringBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(3, int64_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeDouble(4, double_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeFloat(5, float_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBool(6, bool_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getStringBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, int64_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, double_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(5, float_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(6, bool_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.Property parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.Property parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.Property parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.Property parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.Property parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.Property parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.Property parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.Property parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.Property parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.Property parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.Property prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.PropertyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.internal_static_RamCloudGraph_Property_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.internal_static_RamCloudGraph_Property_fieldAccessorTable;
      }
      
      // Construct using com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.Property.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        type_ = com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.Property.Type.STRING;
        bitField0_ = (bitField0_ & ~0x00000001);
        string_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        int64_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        double_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000008);
        float_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000010);
        bool_ = false;
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.Property.getDescriptor();
      }
      
      public com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.Property getDefaultInstanceForType() {
        return com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.Property.getDefaultInstance();
      }
      
      public com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.Property build() {
        com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.Property result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.Property buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.Property result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.Property buildPartial() {
        com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.Property result = new com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.Property(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.string_ = string_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.int64_ = int64_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.double_ = double_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.float_ = float_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.bool_ = bool_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.Property) {
          return mergeFrom((com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.Property)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.Property other) {
        if (other == com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.Property.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasString()) {
          setString(other.getString());
        }
        if (other.hasInt64()) {
          setInt64(other.getInt64());
        }
        if (other.hasDouble()) {
          setDouble(other.getDouble());
        }
        if (other.hasFloat()) {
          setFloat(other.getFloat());
        }
        if (other.hasBool()) {
          setBool(other.getBool());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasType()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.Property.Type value = com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.Property.Type.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                type_ = value;
              }
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              string_ = input.readBytes();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              int64_ = input.readInt64();
              break;
            }
            case 33: {
              bitField0_ |= 0x00000008;
              double_ = input.readDouble();
              break;
            }
            case 45: {
              bitField0_ |= 0x00000010;
              float_ = input.readFloat();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              bool_ = input.readBool();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required .RamCloudGraph.Property.Type type = 1;
      private com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.Property.Type type_ = com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.Property.Type.STRING;
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.Property.Type getType() {
        return type_;
      }
      public Builder setType(com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.Property.Type value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.Property.Type.STRING;
        onChanged();
        return this;
      }
      
      // optional string string = 2;
      private java.lang.Object string_ = "";
      public boolean hasString() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getString() {
        java.lang.Object ref = string_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          string_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setString(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        string_ = value;
        onChanged();
        return this;
      }
      public Builder clearString() {
        bitField0_ = (bitField0_ & ~0x00000002);
        string_ = getDefaultInstance().getString();
        onChanged();
        return this;
      }
      void setString(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        string_ = value;
        onChanged();
      }
      
      // optional int64 int64 = 3;
      private long int64_ ;
      public boolean hasInt64() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public long getInt64() {
        return int64_;
      }
      public Builder setInt64(long value) {
        bitField0_ |= 0x00000004;
        int64_ = value;
        onChanged();
        return this;
      }
      public Builder clearInt64() {
        bitField0_ = (bitField0_ & ~0x00000004);
        int64_ = 0L;
        onChanged();
        return this;
      }
      
      // optional double double = 4;
      private double double_ ;
      public boolean hasDouble() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public double getDouble() {
        return double_;
      }
      public Builder setDouble(double value) {
        bitField0_ |= 0x00000008;
        double_ = value;
        onChanged();
        return this;
      }
      public Builder clearDouble() {
        bitField0_ = (bitField0_ & ~0x00000008);
        double_ = 0D;
        onChanged();
        return this;
      }
      
      // optional float float = 5;
      private float float_ ;
      public boolean hasFloat() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public float getFloat() {
        return float_;
      }
      public Builder setFloat(float value) {
        bitField0_ |= 0x00000010;
        float_ = value;
        onChanged();
        return this;
      }
      public Builder clearFloat() {
        bitField0_ = (bitField0_ & ~0x00000010);
        float_ = 0F;
        onChanged();
        return this;
      }
      
      // optional bool bool = 6;
      private boolean bool_ ;
      public boolean hasBool() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public boolean getBool() {
        return bool_;
      }
      public Builder setBool(boolean value) {
        bitField0_ |= 0x00000020;
        bool_ = value;
        onChanged();
        return this;
      }
      public Builder clearBool() {
        bitField0_ = (bitField0_ & ~0x00000020);
        bool_ = false;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:RamCloudGraph.Property)
    }
    
    static {
      defaultInstance = new Property(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:RamCloudGraph.Property)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_RamCloudGraph_PropertyList_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_RamCloudGraph_PropertyList_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_RamCloudGraph_Property_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_RamCloudGraph_Property_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027elementproperties.proto\022\rRamCloudGraph" +
      "\"9\n\014PropertyList\022)\n\010property\030\001 \003(\0132\027.Ram" +
      "CloudGraph.Property\"\302\001\n\010Property\022*\n\004type" +
      "\030\001 \002(\0162\034.RamCloudGraph.Property.Type\022\016\n\006" +
      "string\030\002 \001(\t\022\r\n\005int64\030\003 \001(\003\022\016\n\006double\030\004 " +
      "\001(\001\022\r\n\005float\030\005 \001(\002\022\014\n\004bool\030\006 \001(\010\">\n\004Type" +
      "\022\n\n\006STRING\020\001\022\t\n\005INT64\020\002\022\n\n\006DOUBLE\020\003\022\t\n\005F" +
      "LOAT\020\004\022\010\n\004BOOL\020\005B@\n\'com.tinkerpop.bluepr" +
      "ints.impls.ramcloudB\025ElementPropertyProt" +
      "os"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_RamCloudGraph_PropertyList_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_RamCloudGraph_PropertyList_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_RamCloudGraph_PropertyList_descriptor,
              new java.lang.String[] { "Property", },
              com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.PropertyList.class,
              com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.PropertyList.Builder.class);
          internal_static_RamCloudGraph_Property_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_RamCloudGraph_Property_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_RamCloudGraph_Property_descriptor,
              new java.lang.String[] { "Type", "String", "Int64", "Double", "Float", "Bool", },
              com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.Property.class,
              com.tinkerpop.blueprints.impls.ramcloud.ElementPropertyProtos.Property.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
